# @package model
# Model configuration
name: base_model
manual: false  # If True, model is created with specified parameters (Use only in Problem 3!)
model_save_bool: true  # If true, save model after training
dir: null  # Directory for saved model (will be computed automatically)
